fine_tuning: true
checkpoint_name: baseline_extended/checkpoint_8.pt


name: baseline_extended

nb_epochs: 10
batch_size: 64
lr: 5.e-6
weight_decay: 0.01

gnn_hdim: 300
mlp_hdim: 300

nout: 768
model_name: distilbert-base-uncased
