# ==== Run name ==== #
name: gat_pretrained_nlp_cosine_aug

# ==== Nlp model parameters ==== #
nlp_model_name: distilbert-base-uncased
custom_tokenizer: true
nlp_pretrained: true

# ==== GNN parameters ==== #
gnn_model_name: gat
gnn_num_layers: 6
gnn_hdim: 512
mlp_hdim: 512
gnn_dropout: 0.2

# ==== Output parameters ==== #
nout: 768

# ==== Training parameters ==== #
nb_epochs: 80
batch_size: 128
lr: 2.e-5
weight_decay: 0.01

# ==== Loss/Model options ==== #
norm_loss: False
avg_pool_nlp: False
top_k_loss: null
top_k_scheduler:
  start: null
  end: null
optimizer: adam

# ==== NLP checkpoint ==== #
nlp_checkpoint: checkpoint-7500

# ==== Fine tuning ==== #
fine_tuning: False
checkpoint_name: null

# ==== Transform ==== #
lambda_aug: 0.5
min_aug: 0
max_aug: 1

p_edge_pertubation: 0
edge_pertubation: 0.1

p_graph_sampling: 0
graph_sampling: 0.5

p_features_noise: 0
features_noise: 0.1

p_features_shuffling: 0
features_shuffling: 0.075

p_features_masking: 0
features_masking: 0.15

p_k_hop_subgraph: 1

# ==== Scheduler ==== #
scheduler: exp_decay
eta_min: 1.e-4
wait_epochs: 4
scheduler_decay: 0.5
