# ==== Run name ==== #
name: gat_pretrained_nlp_cosine_aug

# ==== Nlp model parameters ==== #
nlp_model_name: distilbert-base-uncased
custom_tokenizer: true
nlp_pretrained: true

# ==== GNN parameters ==== #
gnn_model_name: gat
gnn_num_layers: 6
gnn_hdim: 512
mlp_hdim: 512
gnn_dropout: 0.2

# ==== Output parameters ==== #
nout: 768

# ==== Training parameters ==== #
nb_epochs: 80
batch_size: 128
lr: 2.e-5
weight_decay: 0.01

# ==== Loss/Model options ==== #
norm_loss: False
avg_pool_nlp: False

# ==== NLP checkpoint ==== #
nlp_checkpoint: checkpoint-7500

# ==== Fine tuning ==== #
fine_tuning: False
checkpoint_name: null

# ==== Transform ==== #
lambda_aug: 1.5
min_aug: 0
max_aug: 5

p_edge_pertubation: 0.2
edge_pertubation: 0.1

p_graph_sampling: 0.2
graph_sampling: 0.1

p_features_noise: 0.2
features_noise: 0.1

p_features_shuffling: 0.2
features_shuffling: 0.075

p_features_masking: 0.2
features_masking: 0.15

# ==== Scheduler ==== #
scheduler: warmup_cosine
warmup_epochs: 2
eta_min: 1.e-8
eta_max: 1.e-4
