# ==== Run name ==== #
name: gat_pretrained_nlp_cosine

# ==== Nlp model parameters ==== #
nlp_model_name: distilbert-base-uncased
custom_tokenizer: true
nlp_pretrained: true

# ==== GNN parameters ==== #
gnn_model_name: gat
gnn_num_layers: 6
gnn_hdim: 512
mlp_hdim: 512
gnn_dropout: 0.2

# ==== Output parameters ==== #
nout: 768

# ==== Training parameters ==== #
nb_epochs: 40
batch_size: 256
lr: 2.e-5
weight_decay: 0.01

# ==== Loss/Model options ==== #
norm_loss: False
avg_pool_nlp: False
top_k_loss: null

# ==== NLP checkpoint ==== #
nlp_checkpoint: checkpoint-7500

# ==== Fine tuning ==== #
fine_tuning: False
checkpoint_name: null

# ==== Transform ==== #
lambda_aug: 0.
min_aug: 0
max_aug: 0

p_edge_pertubation: 0.
edge_pertubation: 0.

p_graph_sampling: 0.
graph_sampling: 0.

p_features_noise: 0.
features_noise: 0.

p_features_shuffling: 0.
features_shuffling: 0.

p_features_masking: 0.
features_masking: 0

p_k_hop_subgraph: 0

# ==== Scheduler ==== #
scheduler: warmup_cosine
warmup_epochs: 2
eta_min: 1.e-8
eta_max: 1.e-4
