# ==== Run name ==== #
name: gat_aug

# ==== Nlp model parameters ==== #
nlp_model_name: distilbert-base-uncased
custom_tokenizer: False
nlp_pretrained: False

# ==== GNN parameters ==== #
gnn_model_name: gat
gnn_num_layers: 6
gnn_hdim: 512
mlp_hdim: 512
gnn_dropout: 0.2

# ==== Output parameters ==== #
nout: 768

# ==== Training parameters ==== #
nb_epochs: 20
batch_size: 64
lr: 2.e-5
weight_decay: 0.01

# ==== Loss/Model options ==== #
norm_loss: False
avg_pool_nlp: False

# ==== NLP checkpoint ==== #
nlp_checkpoint: null

# ==== Fine tuning ==== #
fine_tuning: False
checkpoint_name: null

# ==== Transform ==== #
edge_pertubation: 0.1
graph_sampling: 0.1
features_noise: 0.1
features_shuffling: 0.1
features_masking: 0.2
